var d3_script_ctrl = ($scope) => {
    $scope.bower_components = [
        { src: "bower_components/jquery/dist/jquery.min.js" },
        { src: "bower_components/datatables/media/js/jquery.dataTables.js" },
        { src: "bower_components/datatables/media/js/dataTables.bootstrap4.js" },
        { src: "bower_components/iCheck/icheck.min.js" },
        { src: "bower_components/google-material-color/dist/palette.js" },
        { src: "bower_components/highcharts/highcharts.js" },
        { src: "bower_components/highcharts/highcharts-more.js" },
        { src: "bower_components/highcharts/modules/exporting.js" },
        { src: "bower_components/d3/d3.js" },
        { src: "bower_components/angular/angular.min.js" },
        { src: "bower_components/bootstrap/dist/js/bootstrap.min.js" },
        { src: "bower_components/bootstrap/dist/js/bootstrap.bundle.min.js" },
        { src: "bower_components/ngSmoothScroll/lib/angular-smooth-scroll.js" },
        { src: "js/dimple/dimple.v2.3.0.min.js" },
        { src: "https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" },
        { src: "js/angularjs/0_0app.js" },
        { src: "js/angularjs/0_5utility.js" },
        { src: "js/d3js/1Select_DOM_Elements_using_D3.js" },
        { src: "js/d3js/2DOM_Manipulation_using_D3.js" },
        { src: "js/d3js/3Method_Chaining_in_D3.js" },
        { src: "js/d3js/4Function_of_Data.js" },
        { src: "js/d3js/5Events_in_D3.js" },
        { src: "js/d3js/6Animation_in_D3.js" },
        { src: "js/d3js/7Data_Binding_in_D3.js" },
        { src: "js/d3js/7Data_Binding_in_D3.js" },
        /* ========================================================= */
        { src: "views/d3_app/d3appctrl.js" },
        { src: "views/d3_app/d3_link.ctrl.js" },
        { src: "views/d3_app/d3.service.js" },
        { src: "views/basic/basic.ctrl.js" },
        { src: "views/page_content/page_content.ctrl.js" },
        { src: "views/sidebar_menu/sidebar_menu.ctrl.js" },
        { src: "views/top_container/top_container.ctrl.js" },
        { src: "views/footer_container/footer_container.ctrl.js" },
        { src: "views/polygon/polygon.ctrl.js" },
        { src: "views/circle/circle.ctrl.js" },
        { src: "views/circle/circle.service.js" },
        { src: "views/map_location/map_location.ctrl.js" },
        { src: "views/map_location/map_location.service.js" },
        { src: "views/dimple/dimple.ctrl.js" },
        { src: "views/dimple/dimple.service.js" },
        { src: "views/dimple/mykey.directive.js" },
        { src: "views/tracnghiemtinhcach/tntc.ctrl.js" },
        { src: "views/tracnghiemtinhcach/tntc.crud.js" },
        { src: "views/ModalDemoCtrl/ModalDemoCtrl.js" },
        { src: "views/UdacityRetain/udacity_retain.ctrl.js" },
        { src: "views/UdacityAttendance/udacity_attendance.ctrl.js" },
        { src: "views/cung_hoang_dao/cung_hoang_dao.ctrl.js" },
        /* ======================================================================== */
        { src: "js/directives/d3directive.js" },
        { src: "js/configs/configuration.js" },
        { src: "js/angularjs/0_1directives.js" },
        { src: "js/angularjs/0_2factories.js" },
        { src: "js/angularjs/0_3controllers.js" },
        { src: "js/angularjs/0_4config.js" },
        { src: "js/firebase/firebase.js" },
    ]
}