d3app
    .controller("SELECT_DOM_ELEMENTS_USING_D3", SELECT_DOM_ELEMENTS_USING_D3)
    .controller("DOM_MANIPULATION_USING_D3", DOM_MANIPULATION_USING_D3)
    .controller("METHOD_CHAINING_IN_D3", METHOD_CHAINING_IN_D3)
    .controller("FUNCTION_OF_DATA", FUNCTION_OF_DATA)
    .controller("EVENTS_IN_D3", EVENTS_IN_D3)
    .controller("ANIMATION_IN_D3", ANIMATION_IN_D3)
    .controller("DATA_BINDING_IN_D3", DATA_BINDING_IN_D3)
    .controller("d3_app_ctrl", d3_app_ctrl)
    .controller("sidebar_menu_ctrl", sidebar_menu_ctrl)
    .controller("top_container_ctrl", top_container_ctrl)
    .controller("page_content_ctrl", page_content_ctrl)
    .controller("footer_container_ctrl", footer_container_ctrl)
    .controller("basic_ctrl", basic_ctrl)
    .controller("polygon_ctrl", polygon_ctrl)
    .controller("circle_ctrl", circle_ctrl)
    .controller("map_location_ctrl", map_location_ctrl)
    .controller("dimple_ctrl", dimple_ctrl)
    .controller("trac_nghiem_tinh_cach_ctrl", trac_nghiem_tinh_cach_ctrl)
    .controller("crud_trac_nghiem_tinh_cach_ctrl", crud_trac_nghiem_tinh_cach_ctrl)
    .controller('ModalDemoCtrl', ModalDemoCtrl)
    .controller('ModalInstanceCtrl', ModalInstanceCtrl)
    .controller('udacity_retain_ctrl', udacity_retain_ctrl)
    .controller('udacity_attendance_ctrl', udacity_attendance_ctrl)
    
