d3app
    .controller("SELECT_DOM_ELEMENTS_USING_D3", SELECT_DOM_ELEMENTS_USING_D3)
    .controller("DOM_MANIPULATION_USING_D3", DOM_MANIPULATION_USING_D3)
    .controller("METHOD_CHAINING_IN_D3", METHOD_CHAINING_IN_D3)
    .controller("FUNCTION_OF_DATA", FUNCTION_OF_DATA)
    .controller("EVENTS_IN_D3", EVENTS_IN_D3)
    .controller("ANIMATION_IN_D3", ANIMATION_IN_D3)
    .controller("DATA_BINDING_IN_D3", DATA_BINDING_IN_D3)